[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

[etherscan]
mantle-sepolia = { key = "${MANTLESCAN_API_KEY}", url = "https://api-sepolia.mantlescan.xyz/api", chain = 5003 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
